name: job_hunt_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  cached_network_image: ^3.2.3
  dio: ^5.1.1
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
